-- Insert Categories and Products
INSERT INTO categories (name) VALUES ('חלב') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1001', 'חלב עמיד 3% 1 ליטר', 5.36, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1002', 'חלב עמיד 1% 1 ליטר', 5.5, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1003', 'חלב הומוגני 3% 1 ליטר', 8.04, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1004', 'חלב הומוגני 1% 1 ליטר', 5.74, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1005', 'חלב עמיד 0.5 ליטר 1%', 3.35, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1006', 'חלב עמיד 0.5 ליטר 3%', 3.35, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1123', 'שוקולד ממרח חלבה', 9.9, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1158', 'חלב מהדרין', 4.1, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1162', 'גבינות 50 גרם', 1.1, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1171', 'גבינה לבנה 250 גרם', 4.8, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1172', 'קוטג'' 250 גרם', 4.8, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1173', 'גבינה צהובה', 16.9, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1174', 'גבינה טעמים', 8.5, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1195', 'חלב שקית', 3.95, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1291', 'שוקו שקית', 1.65, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1358', 'חלב ריץ''', 9.9, 1) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO categories (name) VALUES ('קפה') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1007', 'סוכר', 3.5, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1008', 'סוכרזית טבליות 1000 יח', 9.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1009', 'סוכרזית אבקה 1000 יחי', 38, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1010', 'קפה נמס עלית 200 גרם', 18.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1011', 'קפה נמס האג 200 גרם', 29.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1012', 'קפה נמס רד מאג 200 גרם', 21, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1013', 'קפה נמס ארומה 200 גרם', 19.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1014', 'קפה נמס טסטר צ''ויס', 33, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1015', 'קפה נמס טסטר צ''ויס נטול', 38, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1016', 'קפה ברזילאי קלאסי 200 גרם', 33, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1017', 'קפה פלטיניום קולומביאני', 38, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1018', 'קפה פלטיניום אפריקאי', 38, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1019', 'קפה עלית 100 גרם', 5.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1020', 'קפה ואקום/אלאדין 200 גרם', 12.5, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1021', 'קפה רג''ואן 200 גרם', 15.6, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1022', 'קפה עלית מוסדי 1 ק"ג', 38, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1023', 'קפה 1 ק"ג לנדוור', 29.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1024', 'שוקולית', 11.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1025', 'תה ויסוצקי כחול גדול', 15.8, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1026', 'תה 1/100 מוסדי ויסוצקי', 7.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1027', 'תה ויסוצקי 1.5 גרם', 16.8, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1028', 'תה ליפטון', 15.8, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1029', 'תה צמחים 25 יח', 10.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1030', 'תה פירות צמחים 25 יח''', 10.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1031', 'תה ירוק 25 יח', 15.8, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1032', 'תה עלים 100 גרם', 3.6, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1118', 'קפה שחור האג גרם 200', 19.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1121', 'קפה הל', 6.5, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1303', 'סוכר מנות', 44, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1306', '200 קפה שחור עלית גר', 11.5, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1346', 'קפה נמס מנות', 180, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1347', 'קפה שחור מנות 600 יחידות', 280, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1357', 'קפה ציקו', 25.9, 2) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO categories (name) VALUES ('חטיפים') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1035', 'עוגיות מזרחיות', 15.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1036', 'נישנושים', 8.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1037', 'עו'' בייגלה', 11.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1038', 'עוגיות במגש', 8.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1039', 'עוגיות בקרטון', 6.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1040', 'עוגיות בשקית', 12, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1041', 'עוגיות במשקל 1 ק"ג', 13.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1042', 'עו'' בייגלה גדול', 6.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1043', 'עוגיות שוקוצ''יפס חוץ', 16, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1044', 'וופלים 200גרם', 8.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1045', 'עו'' וופלים טעמים עלית', 9.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1046', 'עו'' וופלים מצופים', 4, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1047', 'עו'' וופלים 1.5 ק"ג', 10.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1048', 'עו'' קרם קרקר', 21, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1049', 'עו'' קרקר זהב 1', 4.2, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1050', 'עו'' פתי בר קטן', 2.6, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1051', 'עו'' בורקס / שמרים 1 ק"ג', 28, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1052', 'ערגליות גדול גרם 900', 21, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1122', 'שוקולד השחר', 8.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1141', 'בייגלה שטוחים', 11.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1142', 'שוקולד פרה עלית', 5.5, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1143', 'סוכריות מנטה', 7.5, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1144', 'חטיפי עלית קטנים', 38, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1145', 'חלבה קופסא / משקל', 16, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1146', 'שוקולד צ''יפס אופיס', 11, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1152', 'ופל לואקר', 4.5, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1153', 'קרקר מאנץ''', 6, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1154', 'תפוצ''יפס קטן', 3, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1155', 'קליק', 5.5, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1156', 'עוגיות אוריו', 5.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1157', 'במבה שקית אסם', 4.8, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1159', 'ביסלי', 4.2, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1160', 'קרקול', 10.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1165', 'רולדת שוקולד עלית', 10.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1176', 'עוגת הבית עלית', 13.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1179', 'שוקולד מרסי', 24, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1182', 'עוגיות יורו קרם', 12, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1183', 'עוגיות פילסברי', 13.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1185', 'חטיף אנרגיה', 2.5, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1191', 'במבה ביסלי קטן', 1.5, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1290', 'מסטיק מאסט משקשק', 4, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1298', 'במבה קטן', 1.5, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1300', 'תפוצ''יפס', 6.8, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1308', 'במבה גדול', 4.8, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1309', 'בסלי גדול', 7.8, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1311', 'עו'' במשקל מלוח', 14, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1319', 'עו'' פתי בר גטניו', 6.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1320', 'פיצוחים 1 ק"ג', 70, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1326', 'עו'' ארד במיכל', 16, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1327', 'מטבעות שוקולד ק"ג 1', 42, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1329', 'מיני מנטוס', 16.9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1330', 'ג''ולים מסטיק', 6, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1331', 'עדשים 1 קג סוכריות', 19, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1339', 'פופקורן למיקרוגל', 18, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1340', 'סוכריות לקישוט', 9, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1359', 'אפרופו', 8.8, 3) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO categories (name) VALUES ('משקאות') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1033', 'סירופ ג''ימבו 2 ליטר', 23.7, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1034', 'סירופ דיאט 1 ליטר', 4.2, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1053', 'קוקה קולה 1.5 ליטר', 5.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1054', '1.5 פריגת ליטר', 5.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1055', '1.5 טמפרי ליטר', 3.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1056', '1.5 נסטי תה ליטר', 6.9, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1057', 'מים 1.5 ליטר עדן/נביעות', 2.65, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1058', '0.5 מים ליטר', 2, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1059', '0.5 מים ספורט', 2, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1060', 'פחיות קולה', 2.95, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1061', 'פריגת קטן', 2.95, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1062', '1.5 סודה ליטר', 2, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1063', 'סודה קטן', 2, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1131', 'מיץ ענבים 1 ליטר', 10.9, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1132', 'מיץ ענבים תירוש 1 ליטר', 15.9, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1133', 'מיץ ענבים תירוש קטן', 10.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1134', 'מיץ לימון סחוט', 6.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1135', 'משקה קל פריגת 1.5 ליטר', 6.8, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1136', 'שוופס מים בטעמים 1.5', 6.8, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1137', 'שוופס מוגז עדין 1.5', 6.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1138', 'משקה אנרגיה XL', 3, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1139', 'פחית שוופס', 4.2, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1140', 'ספרינג קרטון 1 ליטר', 6.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1164', 'פחית זירו / קולה ניקול', 3.1, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1180', 'סחוט פריגת 1 ליטר', 14.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1193', 'מארז מים פחיות קטנות', 21, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1194', 'תרכיז פטל ג''אמפ', 14.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1292', 'יין גאטו-נגרו', 30, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1293', 'יין סלקטד כרמל', 28, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1307', 'יין הר חרמון', 36, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1310', 'בירה שחור', 7.5, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1321', 'בירה שחורה קטן', 3.8, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1324', 'יין מרלו/ קברנה סוביניון', 32, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1325', 'יין יוגב', 46.75, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1349', 'יין דלתון סדרת כנען', 39, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1350', 'יין ברקן רזרב', 49, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1351', 'יין יבש קטן', 29, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1356', 'פחיות נקטר', 3.3, 4) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO categories (name) VALUES ('כלים') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1064', '100 כפיות', 6.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1065', '''100 מזלגות יח', 6.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1066', '100 סכינים יח''', 6.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1067', '''100 כפות יח', 6.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1068', '''4000 כפיות גלידה יח', 120, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1069', '''25 כוסות קלקר יח', 3, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1070', '''1000 כוסות קלקר יח', 88, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1071', ''' 1000 כוסות קלקר יחענק', 180, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1072', '''100 כוסות פלסטיק יח', 5.9, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1073', '''1000 כוסות ניר יח', 180, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1074', '''100 כוסות ניר יח', 18, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1075', '''1000 מכסים יח', 99, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1076', '''50 צלחות גדול יח', 9, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1077', '''50 צלחות קטן יח', 7.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1078', 'צלחות צבעוני גדול', 11.9, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1079', 'מרקיות', 7.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1080', '''25 לפתניות יח', 5.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1081', 'מגש אובלי', 1.8, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1082', '''50 כוסות יין יח', 5.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1117', '500 צלחות קלקר יח', 97, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1147', 'כוסות נייר שחור פרימיום', 16.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1148', 'בוחשנים לקפה עץ', 6.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1149', 'צלחות פלסטיק קשיח', 11.9, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1150', 'קעריות מרק פלסטיק', 8.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1151', 'מגשי אלומיניום ענקיים', 6.9, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1163', 'סט סכו"ם מהודר', 24.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1170', 'מזלג פלסטיק שקוף 100 יח', 8.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1177', 'כוס קריסטל לקינוח', 14.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1178', 'קשיות שתייה נייר', 5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1184', 'חמגשיות עם מכסה', 28, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1192', 'צלחות מתכלות קנה סוכר', 15.9, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1314', 'כוסות זכוכית', 2.5, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1342', 'סכום שיק''', 12, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1353', '''1000 מרקיות קלקר יח', 200, 5) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO categories (name) VALUES ('נייר') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1083', 'ניייר טואלט יער גלילים 24', 16, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1084', 'ניייר טואלט יער גלילים 32', 21.3, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1085', 'ניייר טואלט קלין גלילים 48', 46, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1086', '48 נייר טואלט טאצ', 24.8, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1087', 'ניייר טואלט טאצ''', 21.5, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1088', '1/6 נייר מגבת סנו', 0, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1089', 'ניייר מגבת גלילים 1/6', 29, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1090', 'ניייר מגבת תעשייתי', 38, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1091', 'ניייר מגבת תעשייתי ורד', 85, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1092', 'ניייר מגבת צץ רץ יח 4000 ''', 89, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1093', 'מפיות נייר 100 יח'' פשוט', 3.8, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1094', 'מפיות נייר צבעוני 100 יח''', 6.5, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1095', 'מפיות נייר צבעוני ניקול', 7.9, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1096', 'ניייר טישו - בניילון', 3.5, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1097', 'מפיות נייר בתאבון', 4.8, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1098', 'מפיות מגש בתאבון', 0, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1120', 'ניייר טואלט ג''מבו', 66, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1161', 'מפיות אירוח מהודרות', 12.5, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1181', 'ניייר חסכם מוסדי', 42, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1316', 'אסלוניות', 28, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1333', 'ניייר טואלט כלבים', 55, 6) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO categories (name) VALUES ('ניקוי') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1104', 'אקונומיקה כחול 4 ליטר', 7.5, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1105', 'אקונומיקה לבן 4 ליטר', 13.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1106', 'אקונומיקה ג''וול 4 ליטר', 17.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1107', 'אקונומיקה 1 ליטר', 7.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1108', 'חומצה 1 ליטר', 7.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1109', 'נוזל כלים', 8.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1110', 'נוזל כלים פרי', 8.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1111', 'נוזל כלים פלמוליב', 12.5, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1112', 'נוזל רצפות 4 ליטר', 18, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1113', 'נוזל ידים 4 ליטר', 18, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1114', 'נוזל ידים משאבה', 10.5, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1115', 'מטהר אויר', 9.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1116', 'מטהר אויר מוד', 10, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1167', 'כפפות לטקס', 28, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1169', 'מברשת אסלה', 10.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1188', 'מסיר אבנית', 13.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1189', 'נוזל חלונות', 9.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1190', 'מתקן דיספנסר', 70, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1294', 'ספוג פלא', 18.5, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1296', 'ספרי נמלים', 19, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1301', 'נוזל אסלות', 11.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1312', 'סנו ג''ט מגבונים', 23.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1315', 'מגב', 28, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1317', 'סנו אנטיקלאק', 21.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1334', 'פנטסטיק גדול', 28, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1335', 'סנו רהיט', 16.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1336', 'רסס נגב', 19.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1337', 'נוזל הברקה למדיח', 23.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1354', 'שמפו', 11.9, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1355', 'סבון הוואוי/נקה', 2.5, 7) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO categories (name) VALUES ('מזון') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1119', 'קל" ת"ג) פרות E( אפ'' תפו''', 6, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1124', 'מרק זוגות', 6, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1125', 'טונה', 4, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1126', 'מלח לימון קופסה/ שקית', 7.5, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1127', 'רוטב צ''ילי מתוק', 11.9, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1128', 'רוטב סויה', 9.9, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1129', 'שמן זית 750 מ"ל', 32, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1130', 'שמן קנולה / חמניות', 12, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1166', 'אורז פרסי 1 ק"ג', 8.9, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1168', 'רסק עגבניות קופסא', 4.5, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1175', 'מיונז הלמנס', 14.5, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1186', 'קטשופ אסם', 11.9, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1187', 'חרדל', 6.5, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1196', '', 6.5, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1295', 'מרגרינה קופסא', 8.5, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1304', 'קוסקוס', 7.9, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1322', 'עדשים ירוק 1 ק"ג', 7.5, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1313', 'סלט דג מלוח', 19.9, 8) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO categories (name) VALUES ('אריזות') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1099', '50/70 שקיות אשפה', 0, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1100', '50/70 שקיות אשפה משרדי', 0, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1101', 'שקיות אשפה עירוני שחור', 0, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1102', 'שקיות אשפה עירוני תכלת', 0, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1103', 'שקיות גריסה', 0, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1305', '''100 גליל מפה מ', 115, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1323', 'נייר אפיה ענק', 209, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1328', 'נו טאץ', 98, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1332', 'ניר אפיה', 4.5, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1341', 'שקיות מזון', 7.9, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1352', 'אריזות שי', 138.5, 9) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO categories (name) VALUES ('פירות') ON CONFLICT (name) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1297', 'קרש לחיתוך', 18, 10) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1299', 'אבטיח', 2.8, 10) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1318', 'מלון', 4.5, 10) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1343', 'עגבניות שרי סלסלה', 18, 10) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1344', 'חמוציות', 19.9, 10) ON CONFLICT (item_id) DO NOTHING;
INSERT INTO products (item_id, name, price, category_id) VALUES ('1345', 'פותחן ליין', 16, 10) ON CONFLICT (item_id) DO NOTHING;

